"""empty message

Revision ID: 263486cde09d
Revises: 668edead4ec2
Create Date: 2022-09-05 17:50:32.073880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263486cde09d'
down_revision = '668edead4ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('cars_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'type', 'cars', ['cars_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type', type_='foreignkey')
    op.drop_column('type', 'cars_id')
    # ### end Alembic commands ###
